version: '3.1'

services:
  # api:
  #   image: employee-meetings-api:latest
  #   build: .
  #   environment:
  #     JWT_SECRET: ${JWT_SECRET}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #   ports:
  #     - 5000:3000
  #   volumes:
  #     - ./:/usr/src/app
  #   depends_on:
  #     - db

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./dockerData/db_data:/var/lib/postgresql/data
      - ./dockerData/db_log:/var/log

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8081:8080
